name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo:
    description: The target external repo to publish to
    required: false
  files:
    description: A new line seperated list of files add to the external repo
    required: false
  personal-token:
    description: The GitHub token used access the external repo
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
outputs:
  url:
    description: 'URL to the Release HTML Page'
runs:
  using: 'node12'
  main: 'main.js'
