name: 'Release Repo'
description: 'Publish a release to an external release repo'
inputs:
  repo:
    description: The target external repo to publish to
    required: false
  files:
    description: A new line seperated list of files add to the external repo
    required: false
  personal-token:
    description: The GitHub token used access the external repo
    required: true
outputs:
  url:
    description: 'URL to the Release HTML Page'
runs:
  using: 'node12'
  main: 'main.js'
