name: 'Release Repo'
description: 'Publish a release to an external release repo'
inputs:
  repo:
    description: The target external repo to publish to
    required: true
  file:
    description: The zip file to extract into the extract repo
    required: true
  personal-token:
    description: The GitHub token used access the external repo
    required: true
  branch:
    description: Optional name of the branch to push changes to, defaults to master
    required: false
outputs:
  url:
    description: 'URL to the Release HTML Page'
  html_url:
    description: 'URL to the Release HTML Page'
  tag_name:
    description: 'The tag name for the release'
runs:
  using: 'node12'
  main: 'main.js'
